export const DLES = [
  { name: 'Poople', url: 'https://poople.io' },
  { name: 'Heardle 2020s', url: 'https://20s.heardledecades.com' },
  { name: 'Heardle 2010s', url: 'https://heardle10s.com' },
  { name: 'Heardle 2000s', url: 'https://00s.heardledecades.com' },
  { name: 'Heardle 1990s', url: 'https://90s.heardledecades.com' },
  { name: 'Heardle 1980s', url: 'https://80s.heardledecades.com' },
  { name: 'Heardle 1970s', url: 'https://70s.heardledecades.com' },
  { name: 'Heardle Disney', url: 'https://disney.heardledecades.com' },
  { name: 'Heardle TV Themes', url: 'https://tv.heardledecades.xyz' },
  { name: 'Bandle', url: 'https://bandle.app' },
  { name: 'Crosstune', url: 'https://crosstune.io' },
  { name: 'Scrandle', url: 'https://scrandle.com' },
  { name: 'LinkedIn Pinpoint', url: 'https://www.linkedin.com/games/pinpoint' },
  { name: 'TimeGuessr', url: 'https://timeguessr.com' },
  { name: 'Framed', url: 'https://framed.wtf' },
  { name: 'Movie Grid', url: 'https://moviegrid.io' },
  { name: 'AITA Guesser', url: 'https://muhashi.com/aita-guesser/' },
  { name: 'Pokedle', url: 'https://pokedle.com' },
  { name: 'Adoptle', url: 'https://tryhardguides.com/adoptle' },
  { name: 'Cine2Nerdle', url: 'https://www.cinenerdle2.app' },
  { name: 'FoodGuessr', url: 'https://foodguessr.com' },
  { name: 'Bracket City', url: 'https://www.theatlantic.com/games/bracket-city/' },
  { name: 'Redactle', url: 'https://redactle.net' },
  { name: 'Contexto', url: 'https://contexto.me' },
  { name: 'Heardle K-Pop', url: 'https://kpop.heardledecades.com' },
  { name: 'More/Less', url: 'https://lessgames.com/moreless' },
  { name: 'Cheat Sheet', url: 'https://www.ted.com/games/cheat-sheet' },
]